<?php
return [
    /**
     * Generic values are filled when when neither package was able to guess out the value.
     *
     * @var array
     */
    'item_per_pages' => 15,
    'section' => [

        'articles' => [
            'model' => 'Article',
            'title' => 'Pages',
            'icon' => 'newspaper-o',
            'fieldLabel' => 'ID,Parent,Image,Title,Slug,Pub,Show Top menu,Sort,Created At,Updated At',
            'field' => ['id',
                'parent' => ['type' => 'relation', 'relation' => 'parentPage', 'field' => 'title', 'class' => 'col-sm-1'],
                'image' => ['type' => 'image', 'field' => 'image', 'class' => 'col-sm-1 list-image'],
                'title',
                'slug',
                'pub' => ['type' => 'boolean', 'field' => 'pub', 'class' => 'col-sm-1 text-center'],
                'top_menu' => ['type' => 'boolean', 'field' => 'top_menu', 'class' => 'col-sm-1 text-center'],
                'sort' => ['type' => 'editable', 'field' => 'sort', 'class' => 'col-sm-1'],

                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'sort',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '1',
            'view' => '0',
            'selectable' => '1',
            'showMedia' => '1',
            'showMediaCategory' =>'1',
            'showSeo' => '1',
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add','website']
                ],
            ],
        ],
        'contacts' => [
            'model' => 'Contact',
            'icon'  => 'envelope',
            'title' => 'Info request',
            'fieldLabel' => 'ID,Email,Name,Surname,Message,Read,Created At,Updated At',
            'field' => ['id',
                'email'     => ['type' => 'text', 'field' => 'email', 'class' => 'col-sm-2'],
                'name'      => ['type' => 'text', 'field' => 'name', 'class' => 'col-sm-2'],
                'surname'   => ['type' => 'text', 'field' => 'surname', 'class' => 'col-sm-2'],
                'message'   => ['type' => 'text', 'field' => 'message', 'class' => 'col-sm-2'],
                'status'    => ['type' => 'boolean', 'field' => 'status', 'class' => 'col-sm-1 text-center'],
                'created_at'=> ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at'=> ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'name',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '0',
            'create' => '0',
            'copy' => '0',
            'preview' => '0',
            'view' => '0',
            'selectable' => '0',
            'password' => 0,
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true
                ],
            ]
        ],
        'hpsliders' => [
            'model' => 'HpSlider',
            'title' => 'Home Sliders',
            'icon' => 'image',
            'fieldLabel' => 'ID,Image,Title,Slug,Pub,Sort,Created At,Updated At',
            'field' => ['id',
                'image' => ['type' => 'image', 'field' => 'image', 'class' => 'col-sm-1 list-image'],
                'title',
                'slug',
                'is_active' => ['type' => 'boolean', 'field' => 'is_active', 'class' => 'col-sm-1 text-center'],
                'sort' => ['type' => 'editable', 'field' => 'sort', 'class' => 'col-sm-1'],

                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'edit' => '1',
            'orderBy' => 'sort',
            'orderType' => 'ASC',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ],
        ],
        'media' => [
            'model' => 'Media',
            'title' => 'Media',
            'icon' => 'files-o',
            'fieldLabel' => 'ID,Media,Title,Pub,Sort,Created At,Updated At',
            'field' => ['id',
                'image' => ['type' => 'media', 'field' => 'file_name', 'class' => 'col-sm-1 list-image'],
                'title',
                'pub' => ['type' => 'boolean', 'field' => 'pub', 'class' => 'col-sm-1 text-center'],
                'sort' => ['type' => 'editable', 'field' => 'sort', 'class' => 'col-sm-1'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'edit' => '1',
            'orderBy' => 'sort',
            'orderType' => 'ASC',
            'delete' => '1',
            'create' => '0',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ],
        ],
        'news' => [
            'model' => 'News',
            'title' => 'News',
            'icon' => 'bullhorn',
            'fieldLabel' => 'ID,Date,Image,Title,Slug,Pub,Sort,Created At,Updated At',
            'field' => ['id',
                'date',
                'image' => ['type' => 'image', 'field' => 'image', 'class' => 'col-sm-1 list-image'],
                'title',
                'slug',
                'pub' => ['type' => 'boolean', 'field' => 'pub', 'class' => 'col-sm-1 text-center'],
                'sort' => ['type' => 'editable', 'field' => 'sort', 'class' => 'col-sm-1'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'date',
            'orderType' => 'desc',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '1',
            'view' => '0',
            'selectable' => '1',
            'showMedia' => '1',
            'showMediaCategory' =>'1',
            'showSeo' => '1',
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ],
        ],
        'tags' => [
            'model' => 'Tag',
            'title' => 'TagsNews',
            'icon'  => 'tag',
            'fieldLabel' => 'ID,Title,Slug,Created At,Updated At',
            'field' => ['id',
                'title',
                'slug',
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ],
        ],
        'roles' => [
            'model' => 'Role',
            'icon' => 'graduation-cap',
            'title' => 'Roles',
            'fieldLabel' => 'ID,Name,DisplayName, Description,Created At,Updated At',
            'field' => ['id',
                'name' => ['type' => 'editable', 'field' => 'name', 'class' => 'col-sm-2'],
                'display_name' => ['type' => 'editable', 'field' => 'display_name', 'class' => 'col-sm-2'],
                'description' => ['type' => 'text', 'field' => 'description', 'class' => 'col-sm-2'],

                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1'
        ],
        'socials' => [
            'model' => 'Social',
            'icon' => 'users',
            'title' => 'Socialize',
            'fieldLabel' => 'ID,Social,Icon,Link,Active,Created At,Updated At',
            'field' => ['id',
                'title' => ['type' => 'editable', 'field' => 'title', 'class' => 'col-sm-2'],
                'icon' => ['type' => 'editable', 'field' => 'icon', 'class' => 'col-sm-2'],
                'link' => ['type' => 'text', 'field' => 'link', 'class' => 'col-sm-2'],
                'is_active' => ['type' => 'boolean', 'field' => 'is_active', 'class' => 'col-sm-1 text-center'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'sort',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'menu' => [
                'home' => true,
            ],
        ],
        'countries' => [
            'model' => 'Country',
            'title' => 'Country',
            'icon' => 'folder',
            'fieldLabel' => 'ID,Country,ISO CODE,VAT%,Eu,Pub,Updated At',
            'field' => ['id',
                'name' => ['type' => 'editable', 'field' => 'name', 'class' => 'col-sm-1'],
                'country_code' => ['type' => 'editable', 'field' => 'country_code', 'class' => 'col-sm-1'],
                'vat' => ['type' => 'editable', 'field' => 'vat', 'class' => 'col-sm-1'],
                'eu' => ['type' => 'boolean', 'field' => 'eu', 'class' => 'col-sm-1 text-center'],
                'is_active' => ['type' => 'boolean', 'field' => 'is_active', 'class' => 'col-sm-1 text-center'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1 text-center'],
            ],
            'orderBy' => 'name',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '0',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'showMedia' => '0',
            'showSeo' => '0',
            'menu' => [
                'home' => false,
                'top-bar' =>[
                    'show' => false,
                    'action' =>['add']
                ],
            ],
        ],
        'domains' => [
            'model' => 'Domain',
            'title' => 'Finishing Type',
            'icon' => 'folder',
            'fieldLabel' => 'ID,Domain,Title,Value,Pub,Sort,Updated At',
            'field' => ['id',
                'domain',
                'title',
                'value' => ['type' => 'editable', 'field' => 'value', 'class' => 'col-sm-1'],
                'pub' => ['type' => 'boolean', 'field' => 'pub', 'class' => 'col-sm-1 text-center'],
                'sort' => ['type' => 'editable', 'field' => 'sort', 'class' => 'col-sm-1'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1 text-center'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1 text-center'],
            ],
            'orderBy' => 'domain',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'showMedia' => '0',
            'showSeo' => '0',
            'menu' => [
                'home' => false,
                'top-bar' =>[
                    'show' => false,
                    'action' =>['add']
                ],
            ],
        ],
        'settings' => [
            'model' => 'Setting',
            'title' => 'Setting',
            'icon' => 'wrench',
            'fieldLabel' => 'ID,Domain,Key,Value,Description,Updated At',
            'field' => ['id',
                'domain',
                'key',
                'value' => ['type' => 'editable', 'field' => 'value', 'class' => 'col-sm-1'],
                'description' => ['type' => 'editable', 'field' => 'description', 'class' => 'col-sm-3'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1 text-center'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1 text-center'],
            ],
            'orderBy' => 'key',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '0',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'showMedia' => '0',
            'showSeo' => '0',
            'menu' => [
                'home' => false,
                'top-bar' =>[
                    'show' => false,
                    'action' =>['add']
                ],
            ],
        ],
        'users' => [
            'model' => 'User',
            'icon' => 'user',
            'title' => 'Users',
            'fieldLabel' => 'ID,Email,Name,Password,Active,Created At,Updated At',
            'field' => ['id',
                'email' => ['type' => 'editable', 'field' => 'email', 'class' => 'col-sm-2'],
                'name' => ['type' => 'editable', 'field' => 'name', 'class' => 'col-sm-2'],
                'real_password' => ['type' => 'text', 'field' => 'real_password', 'class' => 'col-sm-2'],
                'is_active' => ['type' => 'boolean', 'field' => 'is_active', 'class' => 'col-sm-1 text-center'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'name',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'password' => 1,
            'menu' => [
                'home' => true,
                'top-bar' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ],
        ],
        'adminusers' => [
            'model' => 'AdminUser',
            'icon' => 'users',
            'title' => 'Admin',
            'fieldLabel' => 'ID,Email,Name,Password,Active,Created At,Updated At',
            'field' => ['id',
                'email' => ['type' => 'editable', 'field' => 'email', 'class' => 'col-sm-2'],
                'name' => ['type' => 'editable', 'field' => 'name', 'class' => 'col-sm-2'],
                'real_password' => ['type' => 'text', 'field' => 'real_password', 'class' => 'col-sm-2'],
                'is_active' => ['type' => 'boolean', 'field' => 'is_active', 'class' => 'col-sm-1 text-center'],
                'created_at' => ['type' => 'date', 'field' => 'created_at', 'class' => 'col-sm-1'],
                'updated_at' => ['type' => 'date', 'field' => 'updated_at', 'class' => 'col-sm-1'],
            ],
            'orderBy' => 'name',
            'orderType' => 'ASC',
            'edit' => '1',
            'delete' => '1',
            'create' => '1',
            'copy' => '1',
            'preview' => '0',
            'view' => '0',
            'selectable' => '1',
            'password' => 1,
            'menu' => [

                'tool' =>[
                    'show' => true,
                    'action' =>['add']
                ],
            ]
        ],
    ],
];